[tool.poetry]
name = "quantum-siren"
version = "0.1.0"
description = ""
authors = ["lc3267 <melvin.strobl@kit.edu>"]
readme = "README.md"
packages = [{include = "quantum_siren"}]

[tool.poetry.dependencies]
python = "^3.10"
pennylane = "^0.31.0"
pillow = "^10.0.0"
scikit-image = "^0.21.0"
ipykernel = "^6.25.0"
torchvision = "^0.15.2+cpu"
matplotlib = "^3.7.2"


[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cpu"
default = false
secondary = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
