training: #see globals.yml for adjustment of n_qubits, n_layers,...
  n_qubits: 4
  n_layers: 14
  #circuit_18, circuit_19, strongly_entangling_layers
  vqc_ansatz: "circuit_19" 
  iec_ansatz: "default"
  data_reupload: 1.0
  learning_rate: 0.07
  shots: "None"
  optimizer: "Adam"
  steps: 400
  report_figure_every_n_steps: 50
  loss: "mse" #mse, fft_ssim, ssim, psnr
  output_interpretation: 0 # -1 to use all qubits or a specific qubit number
  seed: 1111
  max_workers: "None"
