# This is a boilerplate parameters config generated for pipeline 'preprocessing'
# using Kedro 0.18.12.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.18.12/kedro_project_setup/configuration.html#parameters

preprocessing:
  batch_size: -1
  mode: "cosine" # image, cosine
  domain: [-0.7,0.7] # domain of x values
  scale_domain_by_pi: True

  # 'image' mode parameter
  sidelength: 11
  nonlinear_coords: False

  # 'cosine' mode parameter
  # Frequencies for the fourier series
  # Up to 3 dim allowed but each dimension must have the same length.
  # Different lenghts are supported by using '0's as placeholder
  omega: [[1.0,2.0,3.0,4.0], [1.0,2.0,3.0,0.0], [1.0,2.0,0.0,0.0]] 