training: #see globals.yml for adjustment of n_qubits, n_layers,...
  n_qubits: 8
  n_layers: 22
  circuit_type: "Circuit_19" 
  data_reupload: 1.0
  learning_rate: 0.05
  shots: -1
  optimizer: "Adam"
  steps: 400
  report_figure_every_n_steps: 50
  loss: "mse" #mse, fft_ssim, ssim, psnr
  output_qubit: 0 # -1 to use all qubits or a specific qubit number
  initialization: "random"
  seed: 1111
  early_stopping: False
