preprocessing:
  batch_size: -1 # -1 for full dataset    
  mode: "image_cameraman" # image_cameraman, image_coffee, image_cat, image_brick, fourierSeries, helmholtz
  domain: [0,1] # domain of x values
  scale_domain_by_pi: True

  # 'helmholtz' parameters
  wavenumber: 4

  sidelength: 14
  nonlinear_coords: False

  # 'cosine' mode parameter
  # Frequencies for the fourier series
  # Up to 3 dim allowed but each dimension must have the same length.
  # Different lenghts are supported by using '0's as placeholder
  omega: [[1.0,2.0,3.0,4.0], [1.0,2.0,3.0,0.0], [1.0,2.0,0.0,0.0]] 