# This is a boilerplate parameters config generated for pipeline 'training'
# using Kedro 0.18.12.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.18.12/kedro_project_setup/configuration.html#parameters

training:
  n_layers: 12
  n_qubits: 7
  vqc_ansatz: "circuit_19"
  iec_ansatz: "spread_layers"
  data_reupload: True
  learning_rate: 0.001
  shots: None
  steps: 200