# This is a boilerplate parameters config generated for pipeline 'training'
# using Kedro 0.18.12.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.18.12/kedro_project_setup/configuration.html#parameters

training: #see globals.yml for adjustment of n_qubits, n_layers,...
  n_qubits: 10
  n_layers: 22
  vqc_ansatz: "circuit_19"
  iec_ansatz: "spread_layers"
  data_reupload: 1.0
  learning_rate: 0.05
  shots: "None"
  optimizer: "Adam"
  steps: 150
  report_figure_every_n_steps: 20
  loss: "mse" #mse, fft_ssim, ssim, psnr
  output_interpretation: "all" # "all" or a specific qubit number
  max_processes: 4
  max_threads: 4
  seed: 1111
